services:
  mysql:
    image: mysql:8.4
    ports:
    - 3306:3306
    container_name: snippetbox-mysql
    env_file: .sql.env
    volumes:
      - ./sql-data:/var/lib/mysql

  app:
    image: snippetbox
    build: .
    ports:
    - 8080:8080
    container_name: snippetbox
    env_file: .env